dist: trusty
sudo: required

env:
  gloabl:
    NVIDIA_DRIVER_VERSION=381.22
  matrix:
  - COREOS_TRACK=stable 
  - COREOS_TRACK=beta
  - COREOS_TRACK=alpha

before_script:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo apt-key fingerprint 0EBFCD88
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get install docker-ce=17.06.0~ce-0~ubuntu-xenial
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - curl https://${COREOS_TRACK}.release.core-os.net/amd64-usr/current/version.txt -o version.txt
  - export $(cat version.txt | xargs)
  - curl -s https://hub.docker.com/v2/repositories/${DOCKER_USERNAME}/coreos-nvidia-driver/tags/?page_size=10000 | jq -e "[.results | .[] | .name == \"${COREOS_VERSION}-${NVIDIA_DRIVER_VERSION\"] | any | not" || travis_terminate 0


after_success:
  - docker push ${DOCKER_USERNAME}/coreos-nvidia-driver:${COREOS_VERSION}-${NVIDIA_DRIVER_VERSION}

notifications:
  slack: 
    rooms:
      - d26a:3WFB88N8V6onXGdA4fCwOvd4
    on_success: always 
    on_failure: never 
  email:
    recipients:
      on_success: never
      on_failure: always 
