dist: trusty
sudo: required

env:
  global:
    - NVIDIA_DRIVER_VERSION=384.111
    - IMAGE=coreos-nvidia-driver
  matrix:
    - COREOS_TRACK=stable 
    - COREOS_TRACK=beta
    - COREOS_TRACK=alpha

before_script:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo apt-key fingerprint 0EBFCD88
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get install docker-ce=17.12.0~ce-0~ubuntu
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - curl https://${COREOS_TRACK}.release.core-os.net/amd64-usr/current/version.txt -o version.txt
  - export $(cat version.txt | xargs)

script:
  - docker build --build-arg NVIDIA_DRIVER_VERSION=${NVIDIA_DRIVER_VERSION} --build-arg COREOS_VERSION=${COREOS_VERSION} -t ${DOCKER_USERNAME}/${IMAGE}:${COREOS_VERSION}-${NVIDIA_DRIVER_VERSION} --rm .

after_success:
  - docker push ${DOCKER_USERNAME}/${IMAGE}:${COREOS_VERSION}-${NVIDIA_DRIVER_VERSION}
  - docker push ${DOCKER_USERNAME}/${IMAGE}:${COREOS_TRACK}-${NVIDIA_DRIVER_VERSION}

notifications:
  slack: 
    rooms:
      - d26a:3WFB88N8V6onXGdA4fCwOvd4
    on_success: always 
    on_failure: never 
  email:
    recipients:
      on_success: never
      on_failure: always 
